# Для локальной разработки
version: "3.9"

services:

  api:
    ports:
      - "8000:8000"

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:8.12.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    profiles:
      - infra
